<?php
/**
 * Export the demo content as a SQL file that is safe to publish.
 *
 * A plain mysqldump carries wp_users: real email addresses and password
 * hashes. This leaves accounts out entirely, so the file can live in a repo.
 *
 * Usage: php wp-content/themes/estatein/tools/export-db.php [path.sql]
 *
 * @package Estatein
 */

if ( 'cli' !== php_sapi_name() ) {
	exit( 'This script runs from the command line only.' );
}

$root = dirname( __DIR__, 4 );
require_once $root . '/wp-load.php';

global $wpdb;

$target = isset( $argv[1] ) ? $argv[1] : dirname( __DIR__ ) . '/demo-content/estatein-demo.sql';

/**
 * Tables that hold accounts or runtime state, neither of which belongs in a
 * content export.
 */
$skip = array(
	$wpdb->users,
	$wpdb->usermeta,
	$wpdb->prefix . 'actionscheduler_actions',
	$wpdb->prefix . 'actionscheduler_claims',
	$wpdb->prefix . 'actionscheduler_groups',
	$wpdb->prefix . 'actionscheduler_logs',
);

/**
 * Quote one value for a SQL literal.
 *
 * @param string|null $value Column value.
 * @return string
 */
function estatein_sql_value( $value ) {
	global $wpdb;

	if ( null === $value ) {
		return 'NULL';
	}

	return "'" . $wpdb->_real_escape( $value ) . "'";
}

$tables = $wpdb->get_col( 'SHOW TABLES' ); // phpcs:ignore WordPress.DB.DirectDatabaseQuery
$out    = array();
$rows   = 0;

$out[] = '-- Estatein demo content.';
$out[] = '-- Generated by tools/export-db.php. User accounts are deliberately absent:';
$out[] = '-- create an administrator after importing.';
$out[] = 'SET NAMES utf8mb4;';
// Replaces the session mode outright, which drops the strict and zero-date
// rules that reject WordPress's own 0000-00-00 column defaults on import.
$out[] = "SET SESSION sql_mode = 'NO_AUTO_VALUE_ON_ZERO';";
$out[] = 'SET FOREIGN_KEY_CHECKS = 0;';
$out[] = '';

foreach ( $tables as $table ) {
	if ( 0 !== strpos( $table, $wpdb->prefix ) || in_array( $table, $skip, true ) ) {
		continue;
	}

	$create = $wpdb->get_row( "SHOW CREATE TABLE `{$table}`", ARRAY_N ); // phpcs:ignore WordPress.DB

	$out[] = "DROP TABLE IF EXISTS `{$table}`;";
	$out[] = $create[1] . ';';

	// Transients are a cache: they expire, and exporting them only ships stale
	// data that WordPress would rebuild anyway.
	$where = ( $table === $wpdb->options )
		? "WHERE option_name NOT LIKE '\_transient\_%' AND option_name NOT LIKE '\_site\_transient\_%'"
		: '';

	$data = $wpdb->get_results( "SELECT * FROM `{$table}` {$where}", ARRAY_A ); // phpcs:ignore WordPress.DB

	foreach ( array_chunk( $data, 50 ) as $chunk ) {
		$values = array();

		foreach ( $chunk as $row ) {
			$values[] = '(' . implode( ',', array_map( 'estatein_sql_value', $row ) ) . ')';
			$rows++;
		}

		$columns = '`' . implode( '`,`', array_keys( $chunk[0] ) ) . '`';
		$out[]   = "INSERT INTO `{$table}` ({$columns}) VALUES " . implode( ',', $values ) . ';';
	}

	$out[] = '';
	printf( "  %-34s %d rows\n", $table, count( $data ) );
}

$out[] = 'SET FOREIGN_KEY_CHECKS = 1;';

wp_mkdir_p( dirname( $target ) );
file_put_contents( $target, implode( "\n", $out ) . "\n" );

printf(
	"\n%s\n%d rows, %s\n",
	$target,
	$rows,
	size_format( filesize( $target ) )
);

echo "\nAfter importing, point the site at its own URL:\n";
echo "  UPDATE wp_options SET option_value = 'https://your-site' WHERE option_name IN ('siteurl','home');\n";
echo "then create an administrator, since no accounts are included.\n";
